# Generated by Django 5.0.2 on 2024-11-21 20:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_cart_cartmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartModel',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ProductPhotoModel',
            new_name='ProductPhoto',
        ),
        migrations.RenameModel(
            old_name='WareHouseModel',
            new_name='WareHouse',
        ),
    ]
