# Generated by Django 5.0.2 on 2024-11-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_cartmodel_cart_rename_productmodel_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество доступных товаров'),
        ),
    ]
