# Generated by Django 5.0.2 on 2024-11-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/category_photo', verbose_name='Фото-превью'),
        ),
    ]
