# Generated by Django 5.0.2 on 2024-11-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
    ]
